name: Next App CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT_TOKEN }}
    
    - name: Create .env file
      working-directory: ./next-app
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    
    - name: Build and Push Docker Image
      working-directory: ./next-app
      run: |
        docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository_owner }}/gameslink:latest --push .
        
    - name: Deploy to VPS
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} '
          docker stop gameslink || true
          docker rm gameslink || true
          docker pull ghcr.io/${{ github.repository_owner }}/gameslink:latest
          docker run -d --name gameslink -p 3000:3000 ghcr.io/${{ github.repository_owner }}/gameslink:latest
        '